### ISSUE TITLE
Question: queries.yml syntax

### ISSUE THREAD

**Issue by robtec** [wrouesnel/postgres_exporter#108]
Hi,

on the syntax of the `queries.yml` file, is below a correct example?

```
my-db:
  query: "SELECT total from table"
  metrics:
    - total:
        usage: "COUNTER"
        description: "total description"
```
also, can I have another query from the same db in the same file?

```
my-db:
  query: "SELECT time from table2"
  metrics:
    - time:
        usage: "COUNTER"
        description: "time"
```

Cheers 👍
