### ISSUE TITLE
provide kubernetes example

### ISSUE THREAD

**Issue by bchanan03** [wrouesnel/postgres_exporter#123]
Hi,

Is it possible to add a kubernetes deployment, configmap, secrets examples?
Thanks
Chanan

**Comment by fragtom** [comment]
I could do .. on our productive site we use the following k8s deployment

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-exporter
spec:
  template:
    metadata:
      labels:
        app: postgres-exporter
      name: postgres-exporter
    spec:
      volumes:
      - name: config
        configMap:
          name: postgres-exporter-configmap
      containers:
      - env:
        - name: POSGTRES_ADDR
          valueFrom:
            secretKeyRef:
              key: host
              name: redis
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              key: DATA_SOURCE_NAME
              name: postgres
        image: wrouesnel/postgres_exporter:v0.3.0
        name: postgres-exporter
        args:
         - -extend.query-path=/config/queries.yaml
        ports:
        - containerPort: 9187
          hostPort: 9187
          name: pgexporter
        volumeMounts:
        - name: config
          readOnly: true
          mountPath: /config
      hostNetwork: true
      hostPID: true
```

**Comment by fragtom** [comment]
service 

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-exporter
    k8s-app: postgres-exporter
  name: postgres-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9187
    protocol: TCP
  selector:
    app: postgres-exporter
```

**Comment by fragtom** [comment]
configmap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-configmap
data:
  queries.yaml  : |+
    pg_postmaster:
      query: "SELECT pg_postmaster_start_time as start_time_seconds from pg_postmaster_start_time()"
      metrics:
        - start_time_seconds:
            usage: "GAUGE"
            description: "Time at which postmaster started"
...
```

**Comment by wrouesnel** [comment]
@fragtom I'd love to include these if you can submit them as a PR request. Weirdly I do not use kubernetes at all at the moment so it's a bit of an uphill stretch to figure out a canonical example.

**Comment by bchanan03** [comment]
@wrouesnel i tried to create a new branch and from there to create a PR with K8s examples.
Got 403 error.

postgres-exporter-cm.yml
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-configmap
  labels:
    app: postgres-exporter
    monitoring: prometheus
data:
  queries.yaml  : |+
    pg_postmaster:
      query: "SELECT pg_postmaster_start_time as start_time_seconds from pg_postmaster_start_time()"
      metrics:
        - start_time_seconds:
            usage: "GAUGE"
            description: "Time at which postmaster started"
```

postgres-exporter-secrets.yml
```
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secrets
  labels:
    app: postgres-exporter
    monitoring: prometheus
type: Opaque
data:
  pg.admin.pass: mypasswordsecretsinbase64=
```

postgres-exporter-deployment.yml
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-exporter
  labels:
    app: postgres-exporter
    monitoring: prometheus
spec:
  template:
    metadata:
      labels:
        app: postgres-exporter
        monitoring: prometheus
    spec:
      volumes:
      - name: config
        configMap:
          name: postgres-exporter-configmap
      - name: sql-exporter-pem
        configMap:
          name: rds-ca-config
          items:
          - key: platform.rds.ca.cert
            path: ca-certificates.crt
      containers:
      - env:
        - name: DATA_SOURCE_URI
          value: shared-postgres.c1234lj5yf2312.us-west-2.rds.amazonaws.com:5432/postgres
        - name: DATA_SOURCE_USER
          value: root
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              key: pg.admin.pass
              name: postgres-exporter-secrets
        resources:
          limits:
            cpu: 5m
            memory: 50Mi
          requests:
            cpu: 5m
            memory: 50Mi
        livenessProbe:
          tcpSocket:
            port: pgexporter
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: pgexporter
          initialDelaySeconds: 10
          periodSeconds: 30
        image: wrouesnel/postgres_exporter:v0.3.0
        name: postgres-exporter
        args:
         - -extend.query-path=/config/queries.yaml
        ports:
        - containerPort: 9187
          name: pgexporter
        volumeMounts:
        - name: config
          readOnly: true
          mountPath: /config
        - mountPath: /etc/ssl/certs
          name: sql-exporter-pem
          readOnly: true
```

postgres-exporter-svc.yml`
``
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-exporter
    monitoring: prometheus
  name: postgres-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  ports:
  - name: http-metrics
    port: 9187
    protocol: TCP
  selector:
    app: postgres-exporter
```
