### ISSUE TITLE
pg_database_size limit database

### ISSUE THREAD

**Issue by imatpro** [wrouesnel/postgres_exporter#139]
Hi, 

I have 12 databases in my postgresql instance.

I use parameter : --extend.query-path="query.yaml" 

query.yaml
```
pg_database:
  query: "SELECT pg_database.datname, pg_database_size(pg_database.datname) as size FROM pg_database"
  metrics:
    - datname:
        usage: "LABEL"
        description: "Name of the database"
    - size:
        usage: "GAUGE"
        description: "Disk space used by the database"
```

but in metric page, i have only 7 databases.

if add `WHERE datname IN ('db1','db2','db3','db4','db5','db6','db7','db8','db9')` in my query, only first 3 databases in metric pages
or add `WHERE datname NOT IN ('postgres','template0','template1)` same only first 3 databases.

in psql cli, this query (SELECT pg_database.datname, pg_database_size(pg_database.datname) as size FROM pg_database;) return correct numbers of database.

Could you help me please.
