### ISSUE TITLE
postgres-exporter args on 0.4.1

### ISSUE THREAD

**Issue by bchanan03** [wrouesnel/postgres_exporter#147]
Hi all,

Testing the new v0.4.1 postgres-exporter using the following kubernetes deployment.
And i get the following error:

`postgres_exporter: error: unknown short flag '-e', try --help`

Same deployment but with 0.3.0 works. Has the new version broke the backward compatibility?
Running same deployment by removing the args block - works.  

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-exporter
  labels:
    app: postgres-exporter
    monitoring: prometheus
spec:
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: postgres-exporter
        monitoring: prometheus
    spec:
      volumes:
      - name: config
        configMap:
          name: postgres-exporter-configmap
      - name: sql-exporter-pem
        configMap:
          name: rds-ca-config
          items:
          - key: platform.rds.ca.cert
            path: ca-certificates.crt
      containers:
      - env:
        - name: DATA_SOURCE_URI
          value: my-shared-postgres:5432/postgres
        - name: DATA_SOURCE_USER
          value: root
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              key: pg.admin.pass
              name: postgres-exporter-secrets
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        livenessProbe:
          tcpSocket:
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 30
        image: wrouesnel/postgres_exporter:v0.4.1
        securityContext:
           runAsUser: 5005
        name: postgres-exporter
        args:
         - -extend.query-path=/config/queries.yaml
        ports:
        - containerPort: 9187
          name: metrics
        volumeMounts:
        - mountPath: /config
          name: config
          readOnly: true
        - mountPath: /etc/ssl/certs
          name: sql-exporter-pem
          readOnly: true
```
