### ISSUE TITLE
[Question] Can custom metrics retrieve queries in it?

### ISSUE THREAD

**Issue by SamwiseGambgee** [wrouesnel/postgres_exporter#178]
Hello!
Can adding custom queries such as : "Getting the list of queries running more than 5 mins" is possible?

**Comment by ganievs** [comment]
Yes, but you should to create extension [pg_stat_statements](https://www.postgresql.org/docs/current/static/pgstatstatements.html) before
queries.yaml for example:
```
pg_stat_statements:
  query: "SELECT queryid, datname, left(query, 100) as short_query, sum(calls) as calls, sum(total_time) as total_time, min(min_time) as min_time, max(max_time) as max_time, sum(mean_time*calls)/sum(calls) as mean_time FROM pg_stat_statements JOIN pg_database ON pg_stat_statements.dbid = pg_database.oid group by queryid, short_query, datname"
  metrics:
    - queryid:
        usage: "LABEL"
        description: "Query ID"
    - datname:
        usage: "LABEL"
        description: "Database name"
    - short_query:
        usage: "LABEL"
        description: "Query limited to 100 symbols"
    - calls:
        usage: "COUNTER"
        description: "Number of times executed"
    - total_time:
        usage: "COUNTER"
        description: "Total time spent in the statement, in milliseconds"
    - min_time:
        usage: "GAUGE"
        description: "Minimum time spent in the statement, in milliseconds"
    - max_time:
        usage: "GAUGE"
        description: "Maximum time spent in the statement, in milliseconds"
    - mean_time:
        usage: "GAUGE"
       description: "Mean time spent in the statement, in milliseconds"
```
