### ISSUE TITLE
How to organize custom queries in queries.yml?

### ISSUE THREAD

**Issue by jmreicha** [wrouesnel/postgres_exporter#186]
I just want to clear up an issue of how best to organize my custom `queries.yml` file.  Right now I am creating a new top level metric for each custom query to the database, for example I have the following configuration.

```
    pg_accounts_yearly:
      query: "SELECT count(distinct account) as count FROM accounts WHERE last_login > (CURRENT_DATE - INTERVAL '365 days')"
      metrics:
        - count:
            usage: "GAUGE"
            description: "Number of users in the last year"

    pg_accounts_monthly:
      query: "SELECT count(distinct account) as count FROM account WHERE last_login > (CURRENT_DATE - INTERVAL '30 days')"
      metrics:
        - count:
            usage: "GAUGE"
            description: "Number of users in the last month"
```

I'd like to group these queries together into one top level key but don't know if that's possible?  Is there a better way to do what I'm attempting (sorry my Postgres skills aren't the best)?
