### ISSUE TITLE
add application_name from pg_stat_activity

### ISSUE THREAD

**Issue by adamdecaf** [wrouesnel/postgres_exporter#187]
`pg_stat_activity` includes a column `application_name`, which is useful to help debug connection counts per client. Could we add this to the query? It'll add a bit of cardinality, but adds a lot of value to metrics.

```
 count |        application_name        
-------+--------------------------------
    30 | check-image-repository-service
    30 | institution-theming-repository
```

**Comment by adamdecaf** [comment]
The code looks straightforward enough for me to offer a PR, but I wanted to check if this would be accepted.

**Comment by wrouesnel** [comment]
...I feel like this might be a good candidate for a feature flag.

**Comment by adamdecaf** [comment]
We fixed this by modifying the query. (In chef template)

```
pg_stat_activity_transactions_state:
  query: "SELECT '<%= node['hostname'] %>' as hostname, COUNT(state) AS count, state, application_name, client_addr FROM (SELECT CASE WHEN state = 'idle' THEN 'idle' WHEN state = 'idle in transaction' THEN 'idle_in_transaction' WHEN state = 'idle in transaction (aborted)' THEN 'idle_in_transaction_aborted' WHEN state = 'active' THEN 'active' ELSE 'unknown' END AS state, application_name, client_addr FROM pg_stat_activity) state GROUP BY state, application_name, client_addr"
  metrics:
    - hostname:
        usage: "LABEL"
        description: "Hostname of this postgres server"
    - count:
        usage: "COUNTER"
        description: "Count of transactions in state"
    - state:
        usage: "LABEL"
        description: "Transaction state"
    - application_name:
        usage: "LABEL"
        description: "Application name"
    - client_addr:
        usage: "LABEL"
        description: "IP address of application"
```
