### ISSUE TITLE
Allow caching of query results

### ISSUE THREAD

**Issue by SamSaffron** [wrouesnel/postgres_exporter#210]
Getting pg database size is very expensive, especially if we need to do this across hundreds of dbs.

I would like an optional `cache` property per query that allows us to "remember" the last execution of the query for N seconds... Eg:  

```
pg_database:
  query: " SELECT pg_database.datname, pg_database_size(pg_database.datname) as size FROM pg_database" 
  cache: 3600
  metrics:
    - datname:
        usage: "LABEL"
        description: "Name of the database"
    - size:
        usage: "GAUGE"
        description: "Disk space used by the database"
```

Is there any objection to adding such an optional attribute. 

Currently we have no way of reporting DB size cause if we report it we hammer our DBs into oblivion
