### ISSUE TITLE
collected metric ... was collected before with the same name and label values

### ISSUE THREAD

**Issue by leshik** [wrouesnel/postgres_exporter#219]
Hello,

I've added `pg_stat_statements` metrics as per #35 and now some nodes report with errors like this:
```
...
collected metric pg_stat_statements_calls label:<name:"query" value:"SELECT  \"ar_internal_metadata\".* FROM \"ar_internal_metadata\" WHERE \"ar_internal_metadata\".\"key\" = $1 LIMIT $2" > counter:<value:1 >  was collected before with the same name and label values
...
```
Some others report normally though. What might be the reason?

**Comment by keithf4** [comment]
I think this may have to do with the privileges of the monitoring role. Not every non-superuser role can read all the fields in pg_stat_statements for security reasons. So it causes some of the fields that would distinguish a values as being unique to no longer be unique since it's left as NULL.

I've also found that trying to collect pg_stat_statements queries into prometheus (or any TSDB) can cause the storage requirements to increase drastically, especially if you have large queries. Prometheus isn't really made for storing large, non-repetitive text values like pg_stat_statements can produce efficiently. It's storing the entire query statement for each individual time interval collected.

**Comment by leshik** [comment]
Neither is true in my case – postgres exporter is accesing the database using the superuser (postgres), the database itself is quite small (custom dump is about 27 Mb, compressed), and requests aren’t heavy.

**Comment by keithf4** [comment]
I don't mean the size of the postgres database, I mean the size of the prometheus data store.

You may need to add additional labels then to make each collection metric more unique then. I don't see a dbname or user label in there, so if you ran the same query on multiple databases or by different users, those would be distinct rows in pg_stat_statements, but appear identical if those columns are separated out as different labels.

**Comment by srimaln91** [comment]
I'm experiencing the same issue. Please let me know if anyone has found a solution for this.

**Comment by keithf4** [comment]
As I said above, check the values coming back vs the labels you have set. You may need to add additional labels to make similar values distinct. Every time I've come across this so far, it was a valid error message that I had to correct myself with proper labeling.

**Comment by trezorg** [comment]
https://github.com/wrouesnel/postgres_exporter/blob/master/queries.yaml#L129
There should be grouping by LABEL(query) as there are possible duplicate rows from pg_stat_statements for same query.
I use next snippet:

```
pg_stat_statements:
  query: "SELECT query, sum(calls), sum(total_time) as total_time, min(min_time) as min_time, max(max_time) as max_time, sum(mean_time*calls) / sum(calls) as mean_time, avg(stddev_time) as stddev_time, avg(rows) as rows, avg(shared_blks_hit) as shared_blks_hit, avg(shared_blks_read) as shared_blks_read, avg(shared_blks_dirtied) as shared_blks_dirtied, avg(shared_blks_written) as shared_blks_written, avg(local_blks_hit) as local_blks_hit, avg(local_blks_read) as local_blks_read, avg(local_blks_dirtied) as local_blks_dirtied, avg(local_blks_written) as local_blks_written, avg(temp_blks_read) as temp_blks_read, avg(temp_blks_written) as temp_blks_written, avg(blk_read_time) as blk_read_time, avg(blk_write_time) as blk_write_time FROM pg_stat_statements group by query"
  metrics:
    - query:
        usage: "LABEL"
        description: "Query class"
    - calls:
        usage: "COUNTER"
        description: "Number of times executed"
    - total_time:
        usage: "COUNTER"
        description: "Total time spent in the statement, in milliseconds"
    - min_time:
        usage: "GAUGE"
        description: "Minimum time spent in the statement, in milliseconds"
    - max_time:
        usage: "GAUGE"
        description: "Maximum time spent in the statement, in milliseconds"
    - mean_time:
        usage: "GAUGE"
        description: "Mean time spent in the statement, in milliseconds"
    - stddev_time:
        usage: "GAUGE"
        description: "Population standard deviation of time spent in the statement, in milliseconds"
    - rows:
        usage: "COUNTER"
        description: "Total number of rows retrieved or affected by the statement"
    - shared_blks_hit:
        usage: "COUNTER"
        description: "Total number of shared block cache hits by the statement"
    - shared_blks_read:
        usage: "COUNTER"
        description: "Total number of shared blocks read by the statement"
    - shared_blks_dirtied:
        usage: "COUNTER"
        description: "Total number of shared blocks dirtied by the statement"
    - shared_blks_written:
        usage: "COUNTER"
        description: "Total number of shared blocks written by the statement"
    - local_blks_hit:
        usage: "COUNTER"
        description: "Total number of local block cache hits by the statement"
    - local_blks_read:
        usage: "COUNTER"
        description: "Total number of local blocks read by the statement"
    - local_blks_dirtied:
        usage: "COUNTER"
        description: "Total number of local blocks dirtied by the statement"
    - local_blks_written:
        usage: "COUNTER"
        description: "Total number of local blocks written by the statement"
    - temp_blks_read:
        usage: "COUNTER"
        description: "Total number of temp blocks read by the statement"
    - temp_blks_written:
        usage: "COUNTER"
        description: "Total number of temp blocks written by the statement"
    - blk_read_time:
        usage: "COUNTER"
        description: "Total time the statement spent reading blocks, in milliseconds (if track_io_timing is enabled, otherwise zero)"
    - blk_write_time:
        usage: "COUNTER"
        description: "Total time the statement spent writing blocks, in milliseconds (if track_io_timing is enabled, otherwise zero)"
```
