### ISSUE TITLE
Custom queries not working as expected

### ISSUE THREAD

**Issue by hbksagar** [wrouesnel/postgres_exporter#238]
I have appended following snippet to my queries.yml
```
pg_long_running_queries:
  query: "SELECT pid as long_running_pid, now() - pg_stat_activity.query_start as long_running_duration, query as long_running_query, state as long_running_state FROM pg_stat_activity where now() - query_start > interval '5 minute' AND state != 'idle'"
  metrics:
    - long_running_pid:
        usage: "LABEL"
        description: "PID of the long running query"
    - long_running_duration:
        usage: "GAUGE"
        description: "Duration of the long running query"
    - long_running_query:
        usage: "LABEL"
        description: "Long running query"
    - long_running_state:
        usage: "LABEL"
        description: "State of the long running query"
```

Though there exist output in Postgres, there is no info in exporter output.

By mistake I incorrectly added metrics names then I started getting some output but wasn't useful
```
pg_long_running_queries:
  query: "SELECT pid as long_running_pid, now() - pg_stat_activity.query_start as long_running_duration, query as long_running_query, state as long_running_state FROM pg_stat_activity where now() - query_start > interval '5 minute' AND state != 'idle'"
  metrics:
    - pid:
        usage: "LABEL"
        description: "PID of the long running query"
    - duration:
        usage: "GAUGE"
        description: "Duration of the long running query"
    - query:
        usage: "LABEL"
        description: "Long running query"
    - state:
        usage: "LABEL"
        description: "State of the long running query"
```

Output because of above query:
```
# HELP long_running_queries_long_running_pid Unknown metric from long_running_queries
# TYPE long_running_queries_long_running_pid untyped
long_running_queries_long_running_pid{pid="7905",query="7905",state="7905"} 7905
long_running_queries_long_running_pid{pid="7906",query="7906",state="7906"} 7906
```

Am I using this correctly?
