### ISSUE TITLE
PG_EXPORTER_CONSTANT_LABELS is not working

### ISSUE THREAD

**Issue by darkl0rd** [wrouesnel/postgres_exporter#243]
Setting PG_EXPORTER_CONSTANT_LABELS on a service/container does not work.

For example: 

```yml
services:
  postgres-exporter:
    image: .. 
    environment:
      - PG_EXPORTER_CONSTANT_LABELS=name=value
```

Also tried quoting it, or using the dictionary style (PG_EXPORTER_CONSTANT_LABELS: "name=value").
The error is:

`level=error msg="Wrong constant labels format \"\", should be \"key=value\"" source="postgres_exporter.go:934"`
