### ISSUE TITLE
[ Question ] Custom metrics/queries with type COUNTER reset to zero or delete

### ISSUE THREAD

**Issue by kbelosevic** [wrouesnel/postgres_exporter#289]
We are getting some status information about repmgr "replication_db".

Docker swarm config for exporter and its version:
```
  postgres_exporter_replication_status:
    image: wrouesnel/postgres_exporter:v0.4.7
    command: --log.level="debug"
    environment:
    #- PG_EXPORTER_CONTANT_LABELS=node_name=somename,host={pgmaster,pgslave1 or pgslave2}
    - PG_EXPORTER_WEB_LISTEN_ADDRESS=0.0.0.0:9188
    - PG_EXPORTER_EXTEND_QUERY_PATH=/queries.yml
    - PG_EXPORTER_DISABLE_DEFAULT_METRICS="true"
    - PG_EXPORTER_DISABLE_SETTINGS_METRICS="true"
    - DATA_SOURCE_NAME=postgresql://${PG_USER}:${PG_PASSWORD}@postgres_machine:{PORT}/replication_db?sslmode=disable
    networks:
      - network
    volumes:
      - ./postgres-exporter/queries-replication-status.yml:/queries.yml
```

Custom query:
```
pg_replication_metric_3_node_event:
  query: "SELECT node_id, event, CASE WHEN successful THEN '1' ELSE '2' END as status, event_timestamp, details FROM repmgr.events ORDER BY event_timestamp;"
  metrics:
    - node_id:
        usage: "LABEL"
        description: "ID of the node"
    - event:
        usage: "LABEL"
        description: "Event type"
    - status:
        usage: "COUNTER"
        description: "Was action/event successful or not, if true - t return 1 if false -f  return 2"
    - event_timestamp:
        usage: "LABEL"
        description: "Timestamp of the action/event as postgress recorded it"
    - details:
        usage: "LABEL"
        description: "Description of the action/event that happened"
```

Query result:
```
postgres=# \c replication_db 
You are now connected to database "replication_db" as user "postgres".
replication_db=# select * from repmgr.events order by event_timestamp;
 node_id |       event        | successful |        event_timestamp        |                                   details                                    
---------+--------------------+------------+-------------------------------+------------------------------------------------------------------------------
       1 | cluster_created    | t          | 2019-07-15 13:30:50.680715+00 | 
       1 | primary_register   | t          | 2019-07-15 13:30:50.699651+00 | 
```

So what exporter is showing:
```
pg_replication_metric_3_node_event_status{details="",event="cluster_created",event_timestamp="1563197450",node_id="1"} 1
pg_replication_metric_3_node_event_status{details="",event="primary_register",event_timestamp="1563197450",node_id="1"} 1
...... and some more lines .....
pg_replication_metric_3_node_event_status{details="standby registration succeeded (-F/--force option was used)",event="standby_register",event_timestamp="1563197484",node_id="3"} 1
```

My question here is it possible to reset this counter value to 0 or delete it after some time since metric will always be unique because I am setting timestamp in label and counter won't ever go up again.
My issue here is that because after some time repmgr will accumulate a lot of events and with every Prometheus scrape to postgres_exporter list of metrics will just continue to grow and when I am displaying these metrics in Grafana, with every "scrape" of Grafana to Prometheus, Grafana will see a metric (event in my case) that happened, for example, a week ago, like it happened a right now.

What I am trying to accomplish here is to just log unique and initial "value" which was observed only at one point in time so that Prometheus "Graph" shows just "one dot" and not a "continued line (multiple dots)"

The following picture is the current result how prometheus is displaying the values on Graph and "red dot" is my end goal, if possible how I would like to display each individual line which I grab from the postgres_exporter

![prometheus2](https://user-images.githubusercontent.com/11200000/61230356-2d2e8800-a72a-11e9-9257-277adce141e7.png)
