### ISSUE TITLE
No data returned when using non default schema

### ISSUE THREAD

**Issue by TcaManager** [wrouesnel/postgres_exporter#311]
Hi,
I have a database URI like this
```yaml
services:

  postgresql-exporter:
    image: wrouesnel/postgres_exporter:latest
    ports:
      - 9187:9187
    networks:
      - public
    environment:
      - DATA_SOURCE_NAME=postgresql://pgieduct:secretpass@id-devops-7:12111/educonnect?sslmode=disable&search_path=outils
```
This exporter is scraped by prometheus wich is parsed by Grafana.
In Grafana, I added those two DashBoards (I know, I'm lazy)
[PostgreSQL Queries Overview](https://grafana.com/grafana/dashboards/10017)
[PostgreSQL Query Drill-Down](https://grafana.com/grafana/dashboards/10018)

Everything seems to work very fine, but I see no data. I'm thinking the problem is the pg_stat_statements table is not in the default schema, it is in *outils*.

So I tried to define a *search_path* or a *currentSchema* in the URI, but *currentSchema* is not recognized as a valid parameter.

When I connect with the same credentials, with PgAdmin 4, I do this
```sql
SET search_path TO outils;
SELECT * FROM pg_stat_statements;
```
And it works, I can see the content of the table.

userid | dbid | queryid | query
-- | -- | -- | --
10 | 16384 | 297707606 | SELECT oid, format_type(oid, ?) AS typname FROM pg_type
10 | 16384 | 4279036079 | SELECT * FROM outils.pg_stat_statements LIMIT ?
10 | 16384 | 3923712309 | SELECT version();
10 | 16384 | 3388802963 | SELECT ts.oid, spcname, pg_catalog.pg_tablespace_location(ts.oid) AS spclocation, spcoptions, pg_get_userbyid(spcowner) as spcuser, spcacl, pg_catalog.shobj_description(oid, ?) AS description, (SELECT array_agg(label) FROM pg_shseclabel sl1 WHERE sl1.objoid=ts.oid) AS labels, (SELECT array_agg(provider) FROM pg_shseclabel sl2 WHERE sl2.objoid=ts.oid) AS providers FROM pg_tablespace ts ORDER BY spcname
10 | 16384 | 2488260881 | SELECT proname FROM pg_proc WHERE proname=? AND proargtypes[?]=?
10 | 13059 | 2648364664 | SET DateStyle=ISO; SET client_min_messages=notice; SELECT set_config(?,?,?) FROM pg_settings WHERE name = ?; SET client_encoding='UNICODE';
10 | 16384 | 104675863 | SET DateStyle=ISO; SET client_min_messages=notice; SELECT set_config('bytea_output','escape',false) FROM pg_settings WHERE name = 'bytea_output'; SET client_encoding='UNICODE';
10 | 16384 | 506851065 | SELECT name, setting, COALESCE(unit, ?), short_desc, vartype FROM pg_settings WHERE vartype IN (?, ?, ?);
10 | 13059 | 3743991971 | SELECT oid, format_type(oid, ?) AS typname FROM pg_type WHERE oid IN (?, ?, ?, ?) ORDER BY oid;

Any Idea what I did wrong? Is there a way to check in the exporter metrics that this data is read? Thanks. I just need to know if the problem is in my prometheus conf, my exporter conf or my grafana conf. Thanks.
