### ISSUE TITLE
exclude databases not working as expected

### ISSUE THREAD

**Issue by jn-ikharlamov** [wrouesnel/postgres_exporter#343]
Both `PG_EXPORTER_EXCLUDE_DATABASES="template0,template1,postgres"` and cli option `--exclude-databases="template0,template1,postgres"` not excluding metrics for this databases when `PG_EXPORTER_AUTO_DISCOVER_DATABASES=true`
```
$ postgres_exporter --version
postgres_exporter v0.8.0 (built with go1.11)
```

**Comment by sfalkon** [comment]
> Both `PG_EXPORTER_EXCLUDE_DATABASES="template0,template1,postgres"` and cli option `--exclude-databases="template0,template1,postgres"` not excluding metrics for this databases when `PG_EXPORTER_AUTO_DISCOVER_DATABASES=true`
> 
> ```
> $ postgres_exporter --version
> postgres_exporter v0.8.0 (built with go1.11)
> ```

How did you check?

It's work fine
```
$ ./postgres_exporter --version
postgres_exporter v0.8.0 (built with go1.11)
```

```
DATA_SOURCE_NAME="postgresql://postgres@localhost:5432/postgres?sslmode=disable,postgresql://postgres@localhost:5433/postgres?sslmode=disable" ./postgres_exporter --auto-discover-databases --exclude-databases=postgres --extend.query-path="queries.yaml"
```

```
$ curl -s http://localhost:9187/metrics | grep pg_stat_user_tables_idx_scan
# HELP pg_stat_user_tables_idx_scan Number of index scans initiated on this table
# TYPE pg_stat_user_tables_idx_scan counter
pg_stat_user_tables_idx_scan{datname="testdb1",relname="t1",schemaname="public",server="localhost:5432"} NaN
pg_stat_user_tables_idx_scan{datname="testdb2",relname="t1",schemaname="public",server="localhost:5432"} NaN
```

**Comment by jn-ikharlamov** [comment]
I've tried with env vars
```
export DATA_SOURCE_NAME="postgresql://${REPMGR_USER}@localhost:5432/${REPMGR_DB}?sslmode=disable"
export PG_EXPORTER_WEB_LISTEN_ADDRESS="0.0.0.0:9187"
export PG_EXPORTER_DISABLE_SETTINGS_METRICS=false
export PG_EXPORTER_AUTO_DISCOVER_DATABASES=true
export PG_EXPORTER_EXCLUDE_DATABASES="template0,template1,postgres"

postgres_exporter
```

```
curl -s http://localhost:9187/metrics | grep pg_stat_database_numbackends
# HELP pg_stat_database_numbackends Number of backends currently connected to this database. This is the only column in this view that returns a value reflecting current state; all other columns return the accumulated values since the last reset.
# TYPE pg_stat_database_numbackends gauge
pg_stat_database_numbackends{datid="1",datname="template1",server="localhost:5432"} 0
pg_stat_database_numbackends{datid="13066",datname="template0",server="localhost:5432"} 0
pg_stat_database_numbackends{datid="13067",datname="postgres",server="localhost:5432"} 0
pg_stat_database_numbackends{datid="16385",datname="repmgr_db",server="localhost:5432"} 3
pg_stat_database_numbackends{datid="16386",datname="db1",server="localhost:5432"} 1
```


And also tested it with cli options
```
postgres_exporter --auto-discover-databases --exclude-databases="template0,template1,postgres"
```

```
$ curl -s http://localhost:9187/metrics | grep pg_stat_database_numbackends
# HELP pg_stat_database_numbackends Number of backends currently connected to this database. This is the only column in this view that returns a value reflecting current state; all other columns return the accumulated values since the last reset.
# TYPE pg_stat_database_numbackends gauge
pg_stat_database_numbackends{datid="1",datname="template1",server="localhost:5432"} 0
pg_stat_database_numbackends{datid="13066",datname="template0",server="localhost:5432"} 0
pg_stat_database_numbackends{datid="13067",datname="postgres",server="localhost:5432"} 0
pg_stat_database_numbackends{datid="16385",datname="repmgr_db",server="localhost:5432"} 3
pg_stat_database_numbackends{datid="16386",datname="db1",server="localhost:5432"} 1
```

**Comment by sfalkon** [comment]
But it's Ok!
Flag --exclude-databases doesn't filter a query result. If you will call `select * from pg_stat_database` to any database on instance, you will see this result.

And you don't need to exlude template0 and template1 database, because templates not include in autoDiscovery.

**Comment by jn-ikharlamov** [comment]
Ok, thanks!

**Comment by psvampa** [comment]
+1

I've created a very small and simple custom query file:
```
    pg_database:
      query: "SELECT pg_database.datname, pg_database_size(pg_database.datname) as size_bytes FROM pg_database"
      master: true
      metrics:
        - datname:
            usage: "LABEL"
            description: "Name of the database"
        - size_bytes:
            usage: "GAUGE"
            description: "Disk space used by the database"

    pg_database_2:
      query: "SELECT pg_database.datname, pg_database_size(pg_database.datname) as size_bytes FROM pg_database WHERE datname = current_database()"
      master: true
      metrics:
        - datname:
            usage: "LABEL"
            description: "Name of the database"
        - size_bytes:
            usage: "GAUGE"
            description: "Disk space used by the database"
```
My expectation on this one. pg_database should provide database and size for all DBs on given instance. pg_database_2 should provide ONLY the databse size on the DB I am connecting to since I explicitly added `WHERE datname = current_database()`

My exporter command and configuration:
`exec postgres_exporter --web.listen-address :9189 --disable-default-metrics --auto-discover-databases --exclude-databases postgres,template0,template1 --extend.query-path /tmp/queries.yaml`

So, according the documentation it should avoid connecting to any of postgres,template0,template1 DBs. Then pg_database_2 should report target DB names and their sizes

Scraping from the exposed metrics:
```
[root@nsoengas-db-0 /]# curl http://localhost:9189/metrics | grep pg_database
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP pg_database_2_size_bytes Disk space used by the database
# TYPE pg_database_2_size_bytes gauge
pg_database_2_size_bytes{datname="postgres",server="localhost:5432"} 7.526936e+06
# HELP pg_database_size_bytes Disk space used by the database
# TYPE pg_database_size_bytes gauge
pg_database_size_bytes{datname="nsoengas",server="localhost:5432"} 7.58428e+06
pg_database_size_bytes{datname="postgres",server="localhost:5432"} 7.526936e+06
pg_database_size_bytes{datname="template0",server="localhost:5432"} 7.414276e+06
pg_database_size_bytes{datname="template1",server="localhost:5432"} 7.414276e+06
100 51180    0 51180    0     0  4543k      0 --:--:-- --:--:-- --:--:-- 4543k
[root@nsoengas-db-0 /]#
```

As you could see pg_database shows all the 4 DB names and sizes as expected. However, pg_database_2 is reporting postgres DB size which is wrong. IMO it should be reporting "nsoengas" DB size.

If somebody have any idea it will be welcome. I've already tested several configuration and input formats on the excluding list

Thank you in advance
