### ISSUE TITLE
Custom query doesn't display results

### ISSUE THREAD

**Issue by leonsery** [wrouesnel/postgres_exporter#348]
Hi,
I use several custom queries. All work good except one - I trying to get schema sizes:

```
pg_schema:
  query: "SELECT schema_name, sum(table_size) as schema_size_bytes FROM (SELECT pg_catalog.pg_namespace.nspname as schema_name, pg_relation_size(pg_catalog.pg_class.oid) as table_size FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON relnamespace = pg_catalog.pg_namespace.oid) t GROUP BY schema_name"
  metrics:
    - schema_name:
        usage: "LABEL"
        description: "Schema name"
    - schema_size_bytes:
        usage: "LABEL"
        description: "Size of schema in bytes"
```
There is no error, but nothing populated from pg_schema.
Mentioned query returns proper data when running in PG Admin.

Please help
