### ISSUE TITLE
cant get metrics, and "malformed dsn"

### ISSUE THREAD

**Issue by 404notfoundhard** [wrouesnel/postgres_exporter#379]
OS version: Centos 7
Postgres version: 9.4.7
postgres_exporter: v0.8.0
Databases in postgres:
 - postgres
 - template0
 - template1
 - pushwoosh

queries.yml:
```
xid_value:
  query: "SELECT datname, age(datfrozenxid) FROM pg_database"
  master: true
  metrics:
    - datname:
	usage: "LABEL"
        description: "Database name"
    - age:
	usage: "GAUGE"
        description: "Max datfrozenxid"

dead_tuples:
  query: "select current_database() as datname, schemaname || '.' || relname tablename, n_dead_tup dead_tuples from pg_stat_user_tables order by 2 desc"
  master: true
  metrics:
    - datname:
         usage: "LABEL"
         description: "Name of database"
    - tablename:
        usage: "LABEL"
        description: "Table name"
    - dead_tuples:
        usage: "GAUGE"
        description: "Dead tuples"
```
unti file:
```
Environment="DATA_SOURCE_NAME=user=postgres host=127.0.0.1 port=5432 sslmode=disable"
#Environment="DATA_SOURCE_NAME=postgresql://postgres@127.0.0.1:5432/pushwoosh?sslmode=disable"
User=postgres
ExecStart=/usr/bin/postgres_exporter --auto-discover-databases  --disable-settings-metrics  --disable-default-metrics  --web.listen-address :9187 --extend.query-path /etc/postgres_exporter/queries-9.yml

```
but in logs(also i tried add dbname=pushwoosh and dbname=postgres, but it didn't work):
```
postgres_exporter[137992]: time="2020-03-06T07:15:59Z" level=info msg="Semantic Version Changed on \"127.0.0.1:5432\": 0.0.0 -> 9.4.7" source="postgres_exporter.go:1405"
postgres_exporter[137992]: time="2020-03-06T07:16:05Z" level=error msg="Error opening connection to database (pushwoosh): malformed dsn \"pushwoosh\"" source="postgres_exporter.go:1474"
postgres_exporter[137992]: time="2020-03-06T07:16:05Z" level=info msg="Starting Server: :9187" source="postgres_exporter.go:1672"

```

if i use DATA_SOURCE_NAME like this
Environment="DATA_SOURCE_NAME=postgresql://postgres@127.0.0.1:5432/pushwoosh?sslmode=disable"

then I get the metrics of the "xid_value_age" parameter
but there are no "dead_tuples" metrics.

And finally, what it "master: true" ? I can't find any information about this flag.
I can assume that this metric will be taken from the database that is specified in DATA_BASE_NAME, right?
