### ISSUE TITLE
extend.query-path default value when postgresql is down

### ISSUE THREAD

**Issue by tiketafif** [wrouesnel/postgres_exporter#397]
hey,

is there any feature that enable the `--extend.query-path` to set the default value if the postgresql is down?

because i have a query path that look like this:
```
pg_is_in_recovery:
  query: "select case when (pg_is_in_recovery = 't') then '1' else '0' end as recovery from pg_is_in_recovery();"
  metrics:
    - recovery:
        usage: "GAUGE"
        description: "check whether postgresql is in recovery mode"
```

the metrics is gone when the postgresql service is down. what i expect is the metrics is still there with a default value even tough the postgresql service is down or not running.

thanks before.
