### ISSUE TITLE
DNS resolution fails when running in Kubernetes

### ISSUE THREAD

**Issue by garrettschmidt** [wrouesnel/postgres_exporter#430]
I deployed `
postgres_exporter` into a Kubernetes cluster with YAML equivalent to [this example](https://github.com/wrouesnel/postgres_exporter/issues/123) for the service, deployment, and configmap.

I see the following in logs:

```
time="2020-09-10T18:22:12Z" level=error msg="Error opening connection to database (postgresql://postgres:PASSWORD_REMOVED@uaa-postgres:5432/postgres?sslmode=disable): dial tcp: lookup uaa-postgres on 127.0.0.53:53: server misbehaving" source="postgres_exporter.go:1474"
```

`uaa-postgres` is a service in the same Kubernetes namespace and cluster but DNS resolution fails in this context.  

Running `kubectl get svc --namespace=kube-system` shows `kube-dns` running on a different IP:

```
NAME              TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
kube-dns          ClusterIP      10.100.132.76    <none>        53/UDP,53/TCP,9153/TCP   45h
```

(The error message above indicates the DNS server IP of `127.0.0.53:53` is being used).

Deployment configuration:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: uaa-postgres-exporter
spec:
  template:
    metadata:
      labels:
        app: uaa-postgres-exporter
      name: uaa-postgres-exporter
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: uaa-postgres-exporter
          image: wrouesnel/postgres_exporter:v0.8.0
          env:
            - name: DATA_SOURCE_URI
              value: uaa-postgres:5432/postgres?sslmode=disable
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: DATA_SOURCE_USER
              value: postgres
          ports:
            - containerPort: 9187
              hostPort: 9187
              name: pgexporter
          volumeMounts:
            - name: config
              readOnly: true
              mountPath: /config
      volumes:
      - name: config
        configMap:
          name: postgres-exporter-configmap
```

Is there any additional configuration I need to add to properly configure DNS?

Thank you!
