### ISSUE TITLE
Extra query on another DB on another schema "relation does not exist"

### ISSUE THREAD

**Issue by dzervas** [wrouesnel/postgres_exporter#447]
I'm trying to export some repmgr metrics from the `repmgr` DB under `repmgr` schema. What I have currently is:

`queries.yaml`
```yaml
---
repmgr_events:
  query: SELECT * FROM repmgr.events
  metrics:
  - eventscnt:
      usage: COUNTER
      description: Number of events
repmgr_nodes:
  query: SELECT node_id,node_name,active,type,priority FROM repmgr.nodes
  metrics:
  - nodescnt:
      usage: COUNTER
      description: Number of nodes
```

The exporter is run with `--log.level="info" --web.listen-address=":9187" --extend.query-path="/etc/queries.yaml"` arguments and `PG_EXPORTER_AUTO_DISCOVER_DATABASES=true` env.

The errors I get are:

```
Error running query on database:  repmgr_events pq: relation \"repmgr.events\" does not exist\n" source="postgres_exporter.go:933
Error running query on database:  repmgr_nodes pq: relation \"repmgr.nodes\" does not exist\n" source="postgres_exporter.go:933
```

I granted access to the exporter user using:

```sql
\c repmgr
-- Be able to connect to the DB
GRANT CONNECT ON DATABASE repmgr TO postgres_exporter;
-- Grant access to existing tables
GRANT USAGE ON SCHEMA repmgr TO postgres_exporter;
GRANT SELECT ON ALL TABLES IN SCHEMA repmgr TO postgres_exporter;
-- Grant access to future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA repmgr GRANT SELECT ON TABLES TO postgres_exporter;
```
