### ISSUE TITLE
Londiste replication query

### ISSUE THREAD

**Issue by saifulmuhajir** [wrouesnel/postgres_exporter#59]
I tried to add query to view londiste replication lag with these:
```
pg_londiste_replication:
  query: "SELECT consumer_name, GREATEST(0, EXTRACT(EPOCH FROM lag)) as londiste_lag, pending_events from pgq.get_consumer_info() where consumer_name !~ 'watermark$'"
  metrics:
    - londiste_lag:
        usage: "GAUGE"
        description: "Londiste lag"
    - pending_events:
        usage: "GAUGE"
description: "Londiste pending events"
```

but ended up error: 

```
INFO[0000] Unparseable column type - discarding:  pg_londiste_replication consumer_name <nil>
  source=postgres_exporter.go:924
```

Tried to change `consumer_name` to `consumer_name::text` but no luck with the same error. 
Did I miss anything?

**Comment by wrouesnel** [comment]
What types are you returning in those columns? We do our best to infer the type but there's a couple of weird ones in postgres which don't have a sensible generic conversion. Can you post sample data?

**Comment by saifulmuhajir** [comment]
Here's the result when selecting manually:
```
 consumer_name | greatest | pending_events 
---------------+----------+----------------
 review-slv    | 3.346639 |             77
```

**Comment by saifulmuhajir** [comment]
I tried to cast the the column but the error persists:
```
SELECT CAST(COALESCE(consumer_name,'') AS TEXT) as consumer_name, 
GREATEST(0, EXTRACT(EPOCH FROM lag))::FLOAT as londiste_lag, 
pending_events 
from pgq.get_consumer_info() where consumer_name !~ 'watermark$'
```

**Comment by wrouesnel** [comment]
Ah, okay - I see the problem. The query you've given returns multiple columns including `consumer_name` - and the exporter tries to parse this as a metric. But text cannot be parsed as a metric - so there's no possible mapping, so it fails.

Try updating your `queries.yml` to this:
```yaml
pg_londiste_replication:
  query: "SELECT consumer_name, GREATEST(0, EXTRACT(EPOCH FROM lag)) as londiste_lag, pending_events from pgq.get_consumer_info() where consumer_name !~ 'watermark$'"
  metrics:
    - consumer_name:
        usage: "LABEL"
        description: "Name of the consumer"
    - londiste_lag:
        usage: "GAUGE"
        description: "Londiste lag"
    - pending_events:
        usage: "GAUGE"
        description: "Londiste pending events"
```
