### ISSUE TITLE
queries.yml to docker

### ISSUE THREAD

**Issue by NikitaZhevnitskiy** [wrouesnel/postgres_exporter#96]
Is it possible to provide quries.yml to docker? 
I don't have GO compilator. 

`docker-compose.yml`
version: '3.1'
services:
  prometheus:
    build: prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - '/var/lib/postgresql/data'
  exporter:
    image: wrouesnel/postgres_exporter
    ports:
      - 9187:9187
    depends_on:
      - db
    environment:
      DATA_SOURCE_NAME: postgresql://postgres:password@docker-vm:5432/postgres

`Dockerfile`
FROM prom/prometheus
ADD prometheus.yml /etc/prometheus/prometheus.yml

`prometheus.yml`
scrape_configs:
  - job_name:       'example-postgres'
    scrape_interval: 5s
    static_configs:
      - targets: ['docker-vm:9187']

**Comment by wrouesnel** [comment]
You just need to bind-mount the extended queries file into the container from your host.
`docker run -v /path/to/queries.yaml:/queries.yaml wrouesnel/postgres_exporter -extend.query-path=/queries.yaml`

Or for docker-compose.yml:
```yaml
exporter:
  image: wrouesnel/postgres_exporter
  ports:
  - 9187:9187
  depends_on:
  - db
  command: "-extend.query-path=/queries.yaml"
  environment:
    DATA_SOURCE_NAME: postgresql://postgres:password@docker-vm:5432/postgres
  volumes:
  - /path/to/queries.yml:/queries.yaml
`
```
